### PR TITLE
[WIP] refactor: updates carbon package versions to latest

### PR DESCRIPTION
**Pull request by ZacharyStair**
pin carbon versions at latest to facilitate packages using them

BREAKING CHANGE: carbon v6 requires react 16.4+

Closes https://github.ibm.com/connections-incubator/pink-components-react/issues/393

### CODE REVIEW

**Review by testradav — APPROVED** [review]
👍

**Comment by srcrawford** [comment]
@ZacharyStair is this fixing issues related to latest builds and usage of icons

```
WARNING in ./node_modules/carbon-components-react/es/components/Notification/Notification.js 408:15-29
"export 'iconErrorSolid' was not found in 'carbon-icons'
 @ ./node_modules/carbon-components-react/es/components/Notification/index.js
 @ ./node_modules/carbon-components-react/es/index.js
 @ ./node_modules/@connections/pink-components-react/es/index.js
 @ ./node_modules/@connections/connections-catalog-components/src/components/InlineFlatNotification.jsx
```

If so would be good to get this merged and published.. Also @j1mie we should review our usage of `latest` ok for ci/cd type pipelines but for this opensource project it may mean we pull in a major release with breaking changes.

We could in a subsequent ticket pin to a major release and manually bump when ready?

**Comment by ZacharyStair** [comment]
@srcrawford @j1mie I'm not seeing that error regarding `iconErrorSolid` but the connections-catalog-components just need `carbon-components-react@6.x.x` (I think specifically `^6.60.0`), so if we want to use an explicit major version that would be reasonable.

**Comment by ZacharyStair** [comment]
I forgot that react 16.4 phased out the old refs, so I went through and updated them all (phew...) I made some minor tweaks to a couple components but I may have missed some styling issues

**Pull request closed without merging**
